<!DOCTYPE html>
<html>
<head>
<title> Overpopulation </title>
</head>
	 <link rel="stylesheet" type="text/css" href="Style.css"/>
	 <div class="title">
	 <body><h1>Overpopulation<h1></body>
	 </div>
		<a href="Overpopulation.html">Home</a>
		<a href="Actions.html">Actions</a>
		<a href="Support.html">Gallery</a>
		<a href="AboutUs.html">Contact Us</a>
		<hr />
		<h2><div class="title2">What is Overpopulation?</h2>
		</div>
		<p>Overpopulation or overabundance is a phenomenon in which a species' population becomes larger than the carrying capacity of its environment. This may be caused by increased birth rates, lower mortality rates, reduced predation or large scale migration, leading to the overabundant species and other animals in the ecosystem competing for food, space, and resources. The animals in an overpopulated area may then be forced to migrate to areas not typically inhabited, or die off without access to necessary resources.
		<br><br>
		<b>Background</b>
		<br>
		In ecology, overpopulation is a concept used primarily in wildlife management. Typically, an overpopulation causes the entire population of the species in question to become weaker, as no single individual is able to find enough food or shelter. As such, overpopulation is thus characterized by an increase in the diseases and parasite-load which live upon the species in question, as the entire population is weaker. Other characteristics of overpopulation are lower fecundity, adverse effects on the environment and lower average body weights. Supplemental feeding of charismatic species or interesting game species is a major problem in causing overpopulation, as is too little hunting or trapping of such species. Management solutions are increasing hunting by making it easier or cheaper for hunters to hunt, forcing landowners to hunt or contract professional hunters, using immunocontraception, promoting the harvest of venison or other wild meats, introducing large predators, poisonings or introducing diseases.
		<br><br>
		A useful tool in wildlife culling is the use of mobile freezer trailers in which to store carcasses. The harvest of meat from wild animals is a sustainable method of creating a circular economy. deer, elephants, gray squirrels, pigeons, and the need to be in close proximity with animals for injection. Oral vaccines do not have the latter limitation, but they are still not as well developed as injectable vaccines. Scotland's deer are stunted, emaciated, and frequently starve in the Spring. Natural ecosystems are extremely complex. The overpopulation of deer in Britain has been caused by legislation making hunting more difficult, but another reason may be the proliferation of forests, used by different deer species to breed and shelter. Forests and parks have caused Britain to be much more forested than it was in recent history, conversion of heath habitat to grassland, In continental Europe roe deer pose a similar problem, although the populations were formerly much less, they have swelled in the 20th century so that although two and a half million are shot each year by hunters in Western Europe alone, as of 1998, the population still appears to be increasing, causing problems for forestry and traffic. In an experiment where roe deer on a Norwegian island was freed from human harvest and predators, the deer showed a doubling of the population each year or two. As new forests were planted in the Netherlands in the 20th century, the population began to expand rapidly. As of 2016 there are some 110,000 deer in the country. Cormorants are estimated to cost the catfish industry in Mississippi alone between $10 million and $25 million annually.
		<br><br>
		It is difficult to know what the numbers of geese were before the 20th century, before human impact presumably altered them. There are a few anecdotal claims from that time of two or three million, but these are likely exaggerations, as that would imply a massive die-off or vast amounts harvested, for which there is no evidence. More likely estimates from the period of 1500 to 1900 are a few hundred thousand animals, which implies that with the exception of Ross's geese, modern populations of geese are many millions more than in pre-industrial levels. Geese profit from agricultural grain crops, and seem to be shifting their habitat preferences to such farmlands. Ironically, the creation of wildlife refuges may have exacerbated this: as geese overpopulations destroyed the Scirpus salt marsh habitats that they were originally restricted to, this has speeded their conversion to adopt new feeding habitats, while maintaining roosting sites in refuges. The creation of wildlife refuges to protect wetland habitats in the continental United States from the 1930s to 1950s seems to have had the effect of disrupting the migration routes, as geese no longer fly as far south to Texas and Louisiana as they once did. Reduction of goose hunting in the US since the 1970s seems to have further had the effect of protecting populations. In Canada hunting has also decreased dramatically, from 43.384% harvest rates in the 1960s to 8% in the 1990s. Nonetheless, when kill rates were compared to populations, hunting alone does not seems to be solely responsible for the increase -weather or a not yet completed shift in habitat preference to agricultural land may also be factors. Although hunting may have formerly been the main factor in maintaining stable populations, ecologists no longer consider it a practical management solution, as public interest in the practice has continued to wane, and the population is now so large that the massive culls needed are unrealistic to ask from the public. Climate change in the Arctic would appear to be an obvious cause for the increase, but when subpopulations are correlated with local climatic increases, this does not seem to hold true, and furthermore, breeding regions seem to be shifting southwards anyway, irrespective of climate change.
		<br>
		In Russia, the problem does not seem to exist, likely due to human harvest and local long-term cooling climate trends in the Russian Far East and Wrangel Island.
		<br><br>
		<b>Pets</b>
		<br>
		In the United States, over half of the households own a dog or a cat. Even with so much pet ownership there is still an issue with pet overpopulation, especially seen in shelters. Because of this problem it is estimated that between 10 and 25 percent of dogs and cats are killed yearly. The animals are killed humanely, but the goal is to greatly lower and eventually completely avoid this. Animals are constantly being moved around or euthanized, so it is difficult to keep track of those numbers across the country. It is becoming universally agreed upon that sterilization is a tool that can help reduce population size so that less offspring are produced in the future With less offspring, pet populations can start to decrease which reduces the amount that get killed each year.
		<br><br>
		In natural ecosystems, predator population growth lags just behind the prey populations. After the prey population crashes, the overpopulation of predators causes the entire population to be subjected to mass starvation. The population of the predator drops, as less young are able to survive into adulthood. This could be considered a perfect time for wildlife managers to allow hunters or trappers to harvest as much of these animals as necessary, for example lynx in Canada, although on the other hand this may impact the ability of the predator to rebound when the prey population begins to exponentially increase again. this is known as the maximum sustainable yield.
		<br><br>
		Predator population growth has the effect of controlling the prey population, and can result in the evolution of prey species in favour of genetic characteristics that render it less vulnerable to predation. In the absence of predators, species are bound by the resources they can find in their environment, but this does not necessarily control overpopulation, at least in the short term. An abundant supply of resources can produce a population boom followed by a population crash. Rodents such as lemmings and voles have such population cycles of rapid growth and subsequent decrease. Snowshoe hares populations similarly cycle dramatically, as did those of one of their predators, the lynx. For some still unexplained reason, such patterns in mammal population dynamics are more prevalent in ecosystems found at more arctic latitudes.
		<br><br>
		<b>Determining population size/density</b> 
		<br>
		When determining whether a population is overpopulated a variety of factors must be looked at. Given complexity of the issue, often it is determined by scientist and wildlife management as to what constitutes such a claim. In many cases scientists will look to food sources and living space to gauge the abundance of a species in a particular area. National parks collect extensive data on the activities and quality of the environment they are established in. This data can be used to track whether a specific species is consuming larger amounts of their desired food source over time. This is done typically in four ways, the first being “total counting”. Researchers will use aerial photography to count large populations in a specific area such as deer, waterfowl, and other “flocking” or “herd” animals. Incomplete counts involve counting a small subsection of a population and extrapolating the data across the whole area. This method will take into account the behavior of the animals such as how much territory a herd may cover, the density of the population, and other potential factors that may come into question.
		<br><br>
		<b>The third method is “indirect counts”</b>
		<br>
		This is done by looking at the environment for signs of animal presence. Typically done by counting fecal matter or dens/nesting of a particular animal. This method is not an accurate method, but gives general counts of a population in a specific locale. Monitoring of waterways and isolated bodies of water provide more frequently updated information on the populations in specific areas. This is done using similar methods to the mark-recapture methods of many land animals. Introduced species
		<br><br>
		The introduction of a foreign species has often caused ecological disturbance, such as when deer and trout were introduced into Argentina, or when rabbits were introduced to Australia and when predators were introduced in turn to attempt to control the rabbits. When an introduced species is so successful that its population begins to increase exponentially and causes deleterious effects to farmers, fisheries or the natural environment, these introduced species are called invasive species. In the case of the Mute swan, Cygnus olor, their population has rapidly spread across much of North America as well as parts of Canada and western Europe. This species of swan has caused much concern for wildlife management as they damage aquatic vegetation, and harass other waterfowl, dislocating them. The population of the Mute swan has seen an average increase of around 10-18% per year which further threatens to impact the areas they inhabit. Management of the species comes in a variety of ways. Similar to overpopulated or invasive species, hunting is one of the most effective methods of population control. Other methods may involve trapping, relocation, or euthanasia.
		<br><br>
		<b>Criticism</b> 
		<br>
		In natural ecosystems, populations naturally expand until they reach the carrying capacity of the environment; if the resources on which they depend are exhausted, they naturally collapse. According to the animal rights movement, calling this an 'overpopulation' is more an ethics question than a scientific fact. Animal rights organisations are commonly critics of ecological systems and wildlife management. Animal rights activists and locals earning income from commercial hunts counter that scientists are outsiders who do not know wildlife issues, and that any slaughter of animals is evil. Despite the ecological effects of overpopulation, wildlife managers may want such high populations in order to satisfy public enjoyment of seeing wild animals.
		
		</p>








</html>
